### ISSUE TITLE
Pytorch 1.7.1 issue: TypeError when initializing network class

### ISSUE THREAD

**Issue by egoosken** [flaport/photontorch#8] opened 2021-02-12 16:46 UTC
TypeError when initializing photontorch.Network class in Pytorch 1.7.1.

NOTE: FourPortArchitecture class is child of photontorch.Network
NOTE: this issue is not about the ModuleAttributeError which does not occur in our photontorch.Network child classes and likely occurs as the network is being initialized empty. These initializations with empty networks are shown to show that the TypeError occurs even in the most minimal case.

![issue with PT_central class](https://user-images.githubusercontent.com/50325060/107795139-963c0e80-6d58-11eb-9091-0b24c8c86e6c.png)

![issue with photontorch class](https://user-images.githubusercontent.com/50325060/107794823-36ddfe80-6d58-11eb-806a-2535aee7bbac.png)

TypeError did not occur in Pytorch 1.6.0:

![working example PT_central class class](https://user-images.githubusercontent.com/50325060/107795326-caafca80-6d58-11eb-8fc9-eeb3a0038a59.png)

![working example photontorch class](https://user-images.githubusercontent.com/50325060/107795724-5295d480-6d59-11eb-8fbb-6e501d611328.png)

**Comment by Ciacconas** [comment] 2021-02-12 17:08
@egoosken Just wondering if you are using the latest version of photontorch?  #7 has some fix about the context manager of photontorch environment.

**Comment by flaport** [comment] 2021-02-13 08:16
Thanks for reporting @egoosken, This is indeed a duplicate of #6 and was solved in #7. 

Please install photontorch 0.4.1 (or higher)

**Closed by flaport** 2021-02-13 08:16 UTC
